// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlMQ1S4Eb-qT_1zKf4iZ52avLf0SLhSkA',
    appId: '1:823956476241:web:029bbb8a354d3720a30370',
    messagingSenderId: '823956476241',
    projectId: 'diamate-61d52',
    authDomain: 'diamate-61d52.firebaseapp.com',
    storageBucket: 'diamate-61d52.firebasestorage.app',
    measurementId: 'G-FBMDN8N2EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQtmMu_l3v7OrR7cQMSNMfllymnB1sxzw',
    appId: '1:823956476241:android:9bdf63362bac81b7a30370',
    messagingSenderId: '823956476241',
    projectId: 'diamate-61d52',
    storageBucket: 'diamate-61d52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMV4_ki0w7333Ot7ZZpPta2BnbTh-Iq_4',
    appId: '1:823956476241:ios:d2762497829182d7a30370',
    messagingSenderId: '823956476241',
    projectId: 'diamate-61d52',
    storageBucket: 'diamate-61d52.firebasestorage.app',
    iosBundleId: 'com.example.diamate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMV4_ki0w7333Ot7ZZpPta2BnbTh-Iq_4',
    appId: '1:823956476241:ios:d2762497829182d7a30370',
    messagingSenderId: '823956476241',
    projectId: 'diamate-61d52',
    storageBucket: 'diamate-61d52.firebasestorage.app',
    iosBundleId: 'com.example.diamate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlMQ1S4Eb-qT_1zKf4iZ52avLf0SLhSkA',
    appId: '1:823956476241:web:3cac75f3dde7c392a30370',
    messagingSenderId: '823956476241',
    projectId: 'diamate-61d52',
    authDomain: 'diamate-61d52.firebaseapp.com',
    storageBucket: 'diamate-61d52.firebasestorage.app',
    measurementId: 'G-V329HQPQQC',
  );
}
